name: CI

on:
  push:
    branches:
     - master
    tags:
      - '*'
  pull_request:
    branches:
     - master
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    name: 'PHP ${{ matrix.php }}, TYPO3 ${{ matrix.typo3 }}, Composer lowest: ${{ matrix.composer_lowest }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'
        typo3:
          - ^12.4.3
          - ^13.4
        composer_lowest:
          - '0'
          - '1'
        include:
          - php: '8.1'
            typo3: ^12.4.3
            composer_lowest: '0'
          - php: '8.1'
            typo3: ^12.4.3
            composer_lowest: '1'

    steps:
      - uses: actions/checkout@v5

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
          TYPO3_VERSION: ${{matrix.typo3}}
          COMPOSER_PREFER_LOWEST: ${{matrix.composer_lowest}}
        run: docker compose run --rm app composer build

      - name: Cleanup
        if: ${{ always() }}
        run: docker compose down --volumes
